%-----------------------------------------------------------------------
% Job saved on 14-Dec-2022 20:49:34 by cfg_util (rev $Rev: 7345 $)
% spm SPM - SPM12 (7771)
% cfg_basicio BasicIO - Unknown
%-----------------------------------------------------------------------
matlabbatch{1}.spm.stats.fmri_spec.dir = { fullfile(pathSubject,'/glm_s3')};
matlabbatch{1}.spm.stats.fmri_spec.timing.units = 'secs';
matlabbatch{1}.spm.stats.fmri_spec.timing.RT =TR;
matlabbatch{1}.spm.stats.fmri_spec.timing.fmri_t = nSlices;
matlabbatch{1}.spm.stats.fmri_spec.timing.fmri_t0 = 18;
%%
matlabbatch{1}.spm.stats.fmri_spec.sess.scans = {
                                                  fullfile(pathSubject,'/nifti/srbold.nii,1')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,2')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,3')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,4')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,5')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,6')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,7')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,8')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,9')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,10')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,11')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,12')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,13')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,14')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,15')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,16')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,17')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,18')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,19')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,20')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,21')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,22')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,23')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,24')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,25')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,26')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,27')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,28')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,29')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,30')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,31')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,32')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,33')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,34')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,35')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,36')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,37')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,38')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,39')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,40')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,41')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,42')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,43')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,44')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,45')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,46')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,47')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,48')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,49')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,50')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,51')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,52')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,53')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,54')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,55')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,56')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,57')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,58')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,59')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,60')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,61')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,62')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,63')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,64')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,65')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,66')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,67')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,68')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,69')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,70')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,71')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,72')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,73')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,74')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,75')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,76')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,77')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,78')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,79')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,80')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,81')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,82')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,83')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,84')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,85')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,86')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,87')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,88')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,89')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,90')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,91')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,92')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,93')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,94')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,95')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,96')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,97')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,98')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,99')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,100')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,101')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,102')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,103')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,104')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,105')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,106')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,107')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,108')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,109')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,110')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,111')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,112')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,113')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,114')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,115')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,116')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,117')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,118')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,119')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,120')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,121')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,122')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,123')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,124')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,125')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,126')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,127')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,128')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,129')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,130')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,131')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,132')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,133')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,134')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,135')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,136')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,137')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,138')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,139')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,140')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,141')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,142')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,143')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,144')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,145')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,146')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,147')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,148')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,149')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,150')           
                                                  fullfile(pathSubject,'/nifti/srbold.nii,151')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,152')
                                                  fullfile(pathSubject,'/nifti/srbold.nii,153')
                                                 };
%%
matlabbatch{1}.spm.stats.fmri_spec.sess.cond = struct('name', {}, 'onset', {}, 'duration', {}, 'tmod', {}, 'pmod', {}, 'orth', {});
matlabbatch{1}.spm.stats.fmri_spec.sess.multi = {''};
matlabbatch{1}.spm.stats.fmri_spec.sess.regress = struct('name', {}, 'val', {});
matlabbatch{1}.spm.stats.fmri_spec.sess.multi_reg = {fullfile(pathSubject,'/physio_out/multiple_regressors.txt')};
matlabbatch{1}.spm.stats.fmri_spec.sess.hpf = 128;
matlabbatch{1}.spm.stats.fmri_spec.fact = struct('name', {}, 'levels', {});
matlabbatch{1}.spm.stats.fmri_spec.bases.hrf.derivs = [0 0];
matlabbatch{1}.spm.stats.fmri_spec.volt = 1;
matlabbatch{1}.spm.stats.fmri_spec.global = 'None';
matlabbatch{1}.spm.stats.fmri_spec.mthresh = 0.8;
matlabbatch{1}.spm.stats.fmri_spec.mask = {''};
matlabbatch{1}.spm.stats.fmri_spec.cvi = 'AR(1)';
matlabbatch{2}.spm.stats.fmri_est.spmmat(1) = cfg_dep('fMRI model specification: SPM.mat File', substruct('.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','spmmat'));
matlabbatch{2}.spm.stats.fmri_est.write_residuals = 0;
matlabbatch{2}.spm.stats.fmri_est.method.Classical = 1;
